# vim:ft=kitty

## name: Custom Tokyo Night (Mixed)
## license: MIT
## author: Folke Lemaitre & Custom

background #13121c
foreground #e4e0ef
selection_background #93cdf6
cursor #93cdf6

selection_foreground #c0caf5
url_color #73daca
cursor_text_color #1a1b26

# Tabs
active_tab_background #7471be
active_tab_foreground #ffffff
inactive_tab_background #15161e
inactive_tab_foreground #545c7e
#tab_bar_background #15161e

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
color0 #343434
color1 #8383ff
color2 #44def5
color3 #75fcdd
color4 #7fb1cc
color5 #85abec
color6 #87d4ed
color7 #ccdcd6

# bright
color8 #9aa59f
color9 #a29eff
color10 #89ecff
color11 #c9fff3
color12 #a7c5d4
color13 #a3bff7
color14 #98e7ff
color15 #ffffff

# extended colors
color16 #85cfff
color17 #93cdf6
color18 #c4c0ff
