#!/usr/bin/env bash

SELECTED=$(find ~/dev ~/.config ~/studys -mindepth 1 -maxdepth 2 -type d | fzf)

if [[ -z $SELECTED ]]; then
    exit 0
fi

TAB_NAME=$(basename "$SELECTED")

kitten @ launch --type=tab --cwd "$SELECTED" --tab-title "$TAB_NAME"
