new_tab dev
layout tall
cd /home/joaocunha50/dev/playground/ctf/pwnable.tw
launch
cd /home/joaocunha50/dev/personal/caelestia-nvim-dotfiles
launch

new_tab explore
layout tall
cd /home/joaocunha50
launch

new_tab configs
layout tall
cd /home/joaocunha50/.config
launch
cd /home/joaocunha50/.config/kitty
launch

new_tab builds
layout tall
cd /home/joaocunha50
launch

