new_tab dev
layout tall
cd /home/joaocunha50/dev/personal/my_dotfiles
launch

new_tab explore
layout tall
cd /home/joaocunha50/dev/experiments/odysseus
launch

new_tab builds
layout tall
cd /home/joaocunha50
launch

new_tab ~configs
layout tall
cd /home/joaocunha50/.config/fish
launch
cd /home/joaocunha50/.config/caelestia
launch

