new_tab dev
layout tall
cd /home/joaocunha50/dev/personal/my_dotfiles
launch

new_tab configs
layout tall
cd /home/joaocunha50/.config/kitty
launch

new_tab study
layout tall
cd /home/joaocunha50/studys/university/investigacao/Secretaria-Virtual
launch

new_tab MEI-AP
layout tall
cd /home/joaocunha50/studys/university/MEI/1_ano/2_sem/AP/Projeto-AP
launch

