shell /usr/bin/fish

notify_on_cmd_finish invisible

font_family JetBrainsMono Nerd Font Mono
font_size 14.0
font_weight 700
bold_font auto
italic_font auto

disable_ligatures never

split_line_width 2

background_opacity 0.70

# Cursor
cursor_shape beam
cursor_beam_thickness 1.6
cursor_blink_interval 0.6

window_padding_width 6
window_margin_width 8
window_border_width 2pt

single_window_margin_width 2

enabled_layouts Tall, *

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Fundo da barra (parte vazia)
tab_bar_background          #16161e

# ABA ATIVA (VERDE PARA TESTE)
active_tab_foreground       #000000
active_tab_background       #00ff00
active_tab_font_style       bold

# ABA INATIVA (As outras)
inactive_tab_foreground     #787c99
inactive_tab_background     #16161e
inactive_tab_font_style     normal

map alt+1  goto_tab 1
map alt+2  goto_tab 2
map alt+3  goto_tab 3
map alt+4  goto_tab 4
map alt+5  goto_tab 5

map f1 new_window_with_cwd

hide_window_decorations no

allow_remote_control yes
listen_on unix:@mykitty

# BEGIN_KITTY_THEME
# Tokyo Night
# include current-theme.conf
# # END_KITTY_THEME
