shell /usr/bin/fish
startup_session session.conf

notify_on_cmd_finish invisible

font_family JetBrainsMono Nerd Font Mono
font_size 13.0
font_weight 800
bold_font auto
italic_font auto
symbol_map U+D000-U+D200 termicons

disable_ligatures never

split_line_width 2

background_opacity 0.78

# Cursor
cursor_shape beam
cursor_beam_thickness 1.6
cursor_blink_interval 0.6

window_padding_width 4
window_margin_width 6
window_border_width 2pt

single_window_margin_width 2

enabled_layouts Tall, *

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom

map ctrl+1  goto_tab 1
map ctrl+2  goto_tab 2
map ctrl+3  goto_tab 3
map ctrl+4  goto_tab 4
map ctrl+5  goto_tab 5

map f1 new_window_with_cwd

hide_window_decorations no

allow_remote_control yes
listen_on unix:@mykitty

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
