

new_tab dev
layout tall
cd /home/joaocunha50/dev
title ~/dev
launch --env "KITTY_WINDOW_ID=1" --env "PWD=/home/joaocunha50" --env "XDG_DATA_DIRS=/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/home/joaocunha50/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share" /usr/bin/fish
focus


new_tab configs
layout tall
cd /home/joaocunha50/.config
title ~/.config
launch --env "KITTY_WINDOW_ID=2" --env "PWD=/home/joaocunha50/.config/kitty" --env "XDG_DATA_DIRS=/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/home/joaocunha50/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share" /usr/bin/fish
focus


new_tab study
layout tall
cd /home/joaocunha50/studys
title ksave ~/studys
launch --env "KITTY_WINDOW_ID=3" --env "PWD=/home/joaocunha50/studys" --env "XDG_DATA_DIRS=/usr/lib/kitty/shell-integration:/usr/lib/kitty/shell-integration:/home/joaocunha50/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share" /usr/bin/fish
focus
