-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 2,
        col = {
            active_border = "0xff99c1f1",
        },
        gaps_out = 15,
    },
})

-- Keybinds
hl.unbind("SUPER + Apostrophe")
hl.bind("SUPER + dead_acute", hl.dsp.layout("splitratio +0.1"), {
    repeating = true,
})
hl.unbind("SUPER + ALT + 1")
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.unbind("SUPER + ALT + 2")
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.unbind("SUPER + ALT + 3")
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.unbind("SUPER + ALT + 4")
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.unbind("SUPER + ALT + 5")
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.unbind("SUPER + ALT + 6")
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.unbind("SUPER + ALT + 7")
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.unbind("SUPER + ALT + 8")
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.unbind("SUPER + ALT + 9")
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.unbind("SUPER + ALT + 0")
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
